-- Create DRUG_Mapper table
DROP TABLE IF EXISTS "DRUG_Mapper";
CREATE TABLE "DRUG_Mapper" (
    "DRUG_ID" INTEGER PRIMARY KEY,
    "primaryid" BIGINT,
    "caseid" BIGINT,
    "DRUG_SEQ" BIGINT,
    "ROLE_COD" VARCHAR(2),
    "PERIOD" VARCHAR(4),
    "DRUGNAME" TEXT,
    "prod_ai" TEXT,
    "NDA_NUM" VARCHAR(200),
    "NOTES" VARCHAR(100),
    "RXAUI" BIGINT,
    "RXCUI" BIGINT,
    "STR" TEXT,
    "SAB" VARCHAR(20),
    "TTY" VARCHAR(20),
    "CODE" VARCHAR(50),
    "remapping_NOTES" VARCHAR(100),
    "remapping_RXAUI" VARCHAR(8),
    "remapping_RXCUI" VARCHAR(8),
    "remapping_STR" TEXT,
    "remapping_SAB" VARCHAR(20),
    "remapping_TTY" VARCHAR(20),
    "remapping_CODE" VARCHAR(50)
);

-- Insert data into DRUG_Mapper (requires faers_a schema access)
INSERT INTO "DRUG_Mapper" (
    "DRUG_ID", "primaryid", "caseid", "DRUG_SEQ", "ROLE_COD", "DRUGNAME", "prod_ai", "NDA_NUM", "PERIOD"
)
SELECT "DRUG_ID", "primaryid", "caseid", "DRUG_SEQ", "ROLE_COD", "DRUGNAME", "prod_ai", "NDA_NUM", "PERIOD"
FROM faers_a."DRUG_Combined"
WHERE "primaryid" IN (SELECT "primaryid" FROM faers_a."ALIGNED_DEMO_DRUG_REAC_INDI_THER");

-- Create RXNATOMARCHIVE table
DROP TABLE IF EXISTS "RXNATOMARCHIVE";
CREATE TABLE "RXNATOMARCHIVE" (
    "RXAUI" VARCHAR(8) NOT NULL,
    "AUI" VARCHAR(10),
    "STR" TEXT NOT NULL,
    "ARCHIVE_TIMESTAMP" VARCHAR(280) NOT NULL,
    "CREATED_TIMESTAMP" VARCHAR(280) NOT NULL,
    "UPDATED_TIMESTAMP" VARCHAR(280) NOT NULL,
    "CODE" VARCHAR(50),
    "IS_BRAND" VARCHAR(1),
    "LAT" VARCHAR(3),
    "LAST_RELEASED" VARCHAR(30),
    "SAUI" VARCHAR(50),
    "VSAB" VARCHAR(40),
    "RXCUI" VARCHAR(8),
    "SAB" VARCHAR(20),
    "TTY" VARCHAR(20),
    "MERGED_TO_RXCUI" VARCHAR(8)
);

-- Create RXNCONSO table
DROP TABLE IF EXISTS "RXNCONSO";
CREATE TABLE "RXNCONSO" (
    "RXCUI" VARCHAR(8) NOT NULL,
    "LAT" VARCHAR(3) NOT NULL DEFAULT 'ENG',
    "TS" VARCHAR(1),
    "LUI" VARCHAR(8),
    "STT" VARCHAR(3),
    "SUI" VARCHAR(8),
    "ISPREF" VARCHAR(1),
    "RXAUI" VARCHAR(8) NOT NULL,
    "SAUI" VARCHAR(50),
    "SCUI" VARCHAR(50),
    "SDUI" VARCHAR(50),
    "SAB" VARCHAR(20) NOT NULL,
    "TTY" VARCHAR(20) NOT NULL,
    "CODE" VARCHAR(50) NOT NULL,
    "STR" TEXT NOT NULL,
    "SRL" VARCHAR(10),
    "SUPPRESS" VARCHAR(1),
    "CVF" VARCHAR(50)
);

-- Create RXNREL table
DROP TABLE IF EXISTS "RXNREL";
CREATE TABLE "RXNREL" (
    "RXCUI1" VARCHAR(8),
    "RXAUI1" VARCHAR(8),
    "STYPE1" VARCHAR(50),
    "REL" VARCHAR(4),
    "RXCUI2" VARCHAR(8),
    "RXAUI2" VARCHAR(8),
    "STYPE2" VARCHAR(50),
    "RELA" VARCHAR(100),
    "RUI" VARCHAR(10),
    "SRUI" VARCHAR(50),
    "SAB" VARCHAR(20) NOT NULL,
    "SL" VARCHAR(1000),
    "DIR" VARCHAR(1),
    "RG" VARCHAR(10),
    "SUPPRESS" VARCHAR(1),
    "CVF" VARCHAR(50)
);

-- Create RXNSAB table
DROP TABLE IF EXISTS "RXNSAB";
CREATE TABLE "RXNSAB" (
    "VCUI" VARCHAR(8),
    "RCUI" VARCHAR(8),
    "VSAB" VARCHAR(40),
    "RSAB" VARCHAR(20) NOT NULL,
    "SON" TEXT,
    "SF" VARCHAR(20),
    "SVER" VARCHAR(20),
    "VSTART" VARCHAR(10),
    "VEND" VARCHAR(10),
    "IMETA" VARCHAR(10),
    "RMETA" VARCHAR(10),
    "SLC" VARCHAR(1000),
    "SCC" VARCHAR(1000),
    "SRL" INTEGER,
    "TFR" INTEGER,
    "CFR" INTEGER,
    "CXTY" VARCHAR(50),
    "TTYL" VARCHAR(300),
    "ATNL" VARCHAR(1000),
    "LAT" VARCHAR(3),
    "CENC" VARCHAR(20),
    "CURVER" VARCHAR(1),
    "SABIN" VARCHAR(1),
    "SSN" TEXT,
    "SCIT" VARCHAR(4000)
);

-- Create RXNSAT table
DROP TABLE IF EXISTS "RXNSAT";
CREATE TABLE "RXNSAT" (
    "RXCUI" VARCHAR(8),
    "LUI" VARCHAR(8),
    "SUI" VARCHAR(8),
    "RXAUI" VARCHAR(9),
    "STYPE" VARCHAR(50),
    "CODE" VARCHAR(50),
    "ATUI" VARCHAR(11),
    "SATUI" VARCHAR(50),
    "ATN" VARCHAR(1000) NOT NULL,
    "SAB" VARCHAR(20) NOT NULL,
    "ATV" VARCHAR(4000),
    "SUPPRESS" VARCHAR(1),
    "CVF" VARCHAR(50)
);

-- Create RXNSTY table
DROP TABLE IF EXISTS "RXNSTY";
CREATE TABLE "RXNSTY" (
    "RXCUI" VARCHAR(8) NOT NULL,
    "TUI" VARCHAR(4),
    "STN" VARCHAR(100),
    "STY" VARCHAR(50),
    "ATUI" VARCHAR(11),
    "CVF" VARCHAR(50)
);

-- Create RXNDOC table
DROP TABLE IF EXISTS "RXNDOC";
CREATE TABLE "RXNDOC" (
    "DOCKEY" VARCHAR(50) NOT NULL,
    "VALUE" VARCHAR(1000),
    "TYPE" VARCHAR(50) NOT NULL,
    "EXPL" VARCHAR(1000)
);

-- Create RXNCUICHANGES table
DROP TABLE IF EXISTS "RXNCUICHANGES";
CREATE TABLE "RXNCUICHANGES" (
    "RXAUI" VARCHAR(8),
    "CODE" VARCHAR(50),
    "SAB" VARCHAR(20),
    "TTY" VARCHAR(20),
    "STR" TEXT,
    "OLD_RXCUI" VARCHAR(8) NOT NULL,
    "NEW_RXCUI" VARCHAR(8) NOT NULL
);

-- Create RXNCUI table
DROP TABLE IF EXISTS "RXNCUI";
CREATE TABLE "RXNCUI" (
    "cui1" VARCHAR(8),
    "ver_start" VARCHAR(40),
    "ver_end" VARCHAR(40),
    "cardinality" VARCHAR(8),
    "cui2" VARCHAR(8)
);

-- Load data using COPY (requires pg_read_server_files privilege)
COPY "RXNATOMARCHIVE" FROM '/data/faers/FAERS_MAK/2.LoadDataToDatabase/RxNorm_full_06052023/rrf/RXNATOMARCHIVE.RRF' WITH (FORMAT CSV, DELIMITER '|', NULL '', HEADER FALSE);
COPY "RXNCONSO" FROM '/data/faers/FAERS_MAK/2.LoadDataToDatabase/RxNorm_full_06052023/rrf/RXNCONSO.RRF' WITH (FORMAT CSV, DELIMITER '|', NULL '', HEADER FALSE);
COPY "RXNREL" FROM '/data/faers/FAERS_MAK/2.LoadDataToDatabase/RxNorm_full_06052023/rrf/RXNREL.RRF' WITH (FORMAT CSV, DELIMITER '|', NULL '', HEADER FALSE);
COPY "RXNSAB" FROM '/data/faers/FAERS_MAK/2.LoadDataToDatabase/RxNorm_full_06052023/rrf/RXNSAB.RRF' WITH (FORMAT CSV, DELIMITER '|', NULL '', HEADER FALSE);
COPY "RXNSAT" FROM '/data/faers/FAERS_MAK/2.LoadDataToDatabase/RxNorm_full_06052023/rrf/RXNSAT.RRF' WITH (FORMAT CSV, DELIMITER '|', NULL '', HEADER FALSE);
COPY "RXNSTY" FROM '/data/faers/FAERS_MAK/2.LoadDataToDatabase/RxNorm_full_06052023/rrf/RXNSTY.RRF' WITH (FORMAT CSV, DELIMITER '|', NULL '', HEADER FALSE);
COPY "RXNDOC" FROM '/data/faers/FAERS_MAK/2.LoadDataToDatabase/RxNorm_full_06052023/rrf/RXNDOC.RRF' WITH (FORMAT CSV, DELIMITER '|', NULL '', HEADER FALSE);
COPY "RXNCUICHANGES" FROM '/data/faers/FAERS_MAK/2.LoadDataToDatabase/RxNorm_full_06052023/rrf/RXNCUICHANGES.RRF' WITH (FORMAT CSV, DELIMITER '|', NULL '', HEADER FALSE);
COPY "RXNCUI" FROM '/data/faers/FAERS_MAK/2.LoadDataToDatabase/RxNorm_full_06052023/rrf/RXNCUI.RRF' WITH (FORMAT CSV, DELIMITER '|', NULL '', HEADER FALSE);

-- Create indexes after data loading
CREATE INDEX "DRUGNAME_INDEX" ON "DRUG_Mapper" ("DRUGNAME");
CREATE INDEX "RXNCONSO_RXCUI" ON "RXNCONSO" ("RXCUI");
CREATE INDEX "RXNCONSO_RXAUI" ON "RXNCONSO" ("RXAUI");
CREATE INDEX "RXNCONSO_SAB" ON "RXNCONSO" ("SAB");
CREATE INDEX "RXNCONSO_TTY" ON "RXNCONSO" ("TTY");
CREATE INDEX "RXNCONSO_CODE" ON "RXNCONSO" ("CODE");
CREATE INDEX "RXNSAT_RXCUI" ON "RXNSAT" ("RXCUI");
CREATE INDEX "RXNSAT_RXAUI" ON "RXNSAT" ("RXCUI", "RXAUI");
CREATE INDEX "RXNREL_RXCUI1" ON "RXNREL" ("RXCUI1");
CREATE INDEX "RXNREL_RXCUI2" ON "RXNREL" ("RXCUI2");
CREATE INDEX "RXNREL_RXAUI1" ON "RXNREL" ("RXAUI1");
CREATE INDEX "RXNREL_RXAUI2" ON "RXNREL" ("RXAUI2");
CREATE INDEX "RXNREL_RELA" ON "RXNREL" ("RELA");
CREATE INDEX "RXNREL_REL" ON "RXNREL" ("REL");
