--THIS FUNCTION REMOVES ALL  NUMERIC CHARACTERS
/* USE FAERS_B */
/* GO */

CREATE FUNCTION CLEARNUMERICCHARACTERS(@STRING NVARCHAR(MAX))
RETURNS NVARCHAR(MAX)
AS
BEGIN
 WHILE PATINDEX('%[0-9]%', @STRING) > 0
  SET @STRING = STUFF(@STRING, PATINDEX('%[0-9]%', @STRING), 1, '')
 RETURN @STRING
END
GO
-------------------------------------------------------------

-- Temporary table with selected columns, and ensuring no duplicates
SELECT DISTINCT DRUGNAME, PROD_AI, CLEANED_DRUGNAME, CLEANED_PROD_AI  
INTO DRUG_Mapper_Temp
FROM DRUG_Mapper
WHERE NOTES IS NULL;

-- INSERT_SEGMENT_1_HERE -- Pharmaceutical company names and brand identifiers for CLEANED_DRUGNAME

UPDATE DRUG_Mapper_Temp
SET CLEANED_DRUGNAME = DBO.CLEARNUMERICCHARACTERS(CLEANED_DRUGNAME)

GO

UPDATE DRUG_Mapper_Temp
SET CLEANED_DRUGNAME =LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(CLEANED_DRUGNAME, CHAR(10), ''), CHAR(13), ''), CHAR(9), '')))
GO

-- INSERT_SEGMENT_2_HERE -- Units of measurement and dosage forms for CLEANED_DRUGNAME

UPDATE DRUG_Mapper_Temp
SET CLEANED_DRUGNAME =  DBO.CLEARNUMERICCHARACTERS(CLEANED_DRUGNAME)

GO


-- INSERT_SEGMENT_3_HERE -- Special characters and pharmaceutical abbreviations for CLEANED_DRUGNAME

UPDATE DRUG_Mapper_Temp
SET CLEANED_DRUGNAME =  TRIM (' ":.,?/\`~!@#$%^&*-_=+ ' FROM CLEANED_DRUGNAME)

GO 

UPDATE DRUG_Mapper_Temp
SET CLEANED_DRUGNAME =  TRIM (' ":.,?/\`~!@#$%^&*-_=+ ' FROM CLEANED_DRUGNAME)
 

 UPDATE DRUG_Mapper_Temp
SET CLEANED_DRUGNAME =LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(CLEANED_DRUGNAME, CHAR(10), ' '), CHAR(13), ' '), CHAR(9), ' ')))
  GO

  
 UPDATE DRUG_Mapper_Temp 
SET CLEANED_DRUGNAME =LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(CLEANED_DRUGNAME, CHAR(10), ' '), CHAR(13), ' '), CHAR(9), ' ')))
  GO

  
 UPDATE DRUG_Mapper_Temp
SET CLEANED_DRUGNAME =LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(CLEANED_DRUGNAME, CHAR(10), ''), CHAR(13), ''), CHAR(9), '')))
  GO

-- INSERT_SEGMENT_4_HERE -- Suffix removal and trailing character cleanup for CLEANED_DRUGNAME

UPDATE DRUG_Mapper_Temp SET CLEANED_DRUGNAME =  LEFT(CLEANED_DRUGNAME, LEN(CLEANED_DRUGNAME)-4) 
WHERE RIGHT (CLEANED_DRUGNAME,4) =' NOS';


UPDATE DRUG_Mapper_Temp SET CLEANED_DRUGNAME =  LEFT(CLEANED_DRUGNAME, LEN(CLEANED_DRUGNAME)-4) 
WHERE RIGHT (CLEANED_DRUGNAME,4) =' GEL';

UPDATE DRUG_Mapper_Temp SET CLEANED_DRUGNAME =  LEFT(CLEANED_DRUGNAME, LEN(CLEANED_DRUGNAME)-4) 
WHERE RIGHT (CLEANED_DRUGNAME,4) =' CAP';

UPDATE DRUG_Mapper_Temp SET CLEANED_DRUGNAME =  LEFT(CLEANED_DRUGNAME, LEN(CLEANED_DRUGNAME)-5) 
WHERE RIGHT (CLEANED_DRUGNAME,5) =' JELL';


UPDATE DRUG_Mapper_Temp SET CLEANED_DRUGNAME =  LEFT(CLEANED_DRUGNAME, LEN(CLEANED_DRUGNAME)-4) 
WHERE RIGHT (CLEANED_DRUGNAME,4) =' TAB';
GO

UPDATE DRUG_Mapper_Temp SET CLEANED_DRUGNAME =  LEFT(CLEANED_DRUGNAME, LEN(CLEANED_DRUGNAME)-4) 

WHERE RIGHT (CLEANED_DRUGNAME,4) =' FOR';
GO

UPDATE DRUG_Mapper_Temp SET CLEANED_DRUGNAME =  LEFT(CLEANED_DRUGNAME, LEN(CLEANED_DRUGNAME)-2) 

WHERE RIGHT (CLEANED_DRUGNAME,2) ='//';
GO

UPDATE DRUG_Mapper_Temp SET CLEANED_DRUGNAME =  LEFT(CLEANED_DRUGNAME, LEN(CLEANED_DRUGNAME)-3) 

WHERE RIGHT (CLEANED_DRUGNAME,1) ='/';
GO


   UPDATE DRUG_Mapper_Temp
SET CLEANED_PROD_AI =LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(CLEANED_PROD_AI, CHAR(10), ''), CHAR(13), ''), CHAR(9), '')))

   UPDATE DRUG_Mapper_Temp
SET CLEANED_PROD_AI =LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(CLEANED_PROD_AI, CHAR(10), ''), CHAR(13), ''), CHAR(9), '')))

   UPDATE DRUG_Mapper_Temp
SET CLEANED_PROD_AI =LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(CLEANED_PROD_AI, CHAR(10), ''), CHAR(13), ''), CHAR(9), '')))

-- INSERT_SEGMENT_5_HERE -- Pharmaceutical company names and brand identifiers for CLEANED_PROD_AI

UPDATE DRUG_Mapper_Temp
SET CLEANED_PROD_AI = DBO.CLEARNUMERICCHARACTERS(CLEANED_PROD_AI)

GO

-- WHITE SPACES
UPDATE DRUG_Mapper_Temp
SET CLEANED_PROD_AI =LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(CLEANED_PROD_AI, CHAR(10), ''), CHAR(13), ''), CHAR(9), '')))

GO


-- INSERT_SEGMENT_6_HERE -- Units of measurement and dosage forms for CLEANED_PROD_AI

UPDATE DRUG_Mapper_Temp
SET CLEANED_PROD_AI =  DBO.CLEARNUMERICCHARACTERS(CLEANED_PROD_AI)

GO

-- INSERT_SEGMENT_7_HERE -- Special characters and pharmaceutical abbreviations for CLEANED_PROD_AI

UPDATE DRUG_Mapper_Temp
SET CLEANED_PROD_AI =  TRIM (' ":.,?/\`~!@#$%^&*-_=+ ' FROM CLEANED_PROD_AI)

GO 

UPDATE DRUG_Mapper_Temp
SET CLEANED_PROD_AI =LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(CLEANED_PROD_AI, CHAR(10), ' '), CHAR(13), ' '), CHAR(9), ' ')))
  GO

  
 UPDATE DRUG_Mapper_Temp
SET CLEANED_PROD_AI =LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(CLEANED_PROD_AI, CHAR(10), ' '), CHAR(13), ' '), CHAR(9), ' ')))
  GO
  
 UPDATE DRUG_Mapper_Temp
SET CLEANED_PROD_AI =LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(CLEANED_PROD_AI, CHAR(10), ' '), CHAR(13), ' '), CHAR(9), ' ')))
  GO

UPDATE DRUG_Mapper_Temp
SET CLEANED_PROD_AI =  TRIM (' ":.,?/\`~!@#$%^&*-_=+ ' FROM CLEANED_PROD_AI)


-- INSERT_SEGMENT_8_HERE -- Suffix removal and trailing character cleanup for CLEANED_PROD_AI

 UPDATE DRUG_Mapper_Temp
SET CLEANED_PROD_AI =LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(CLEANED_PROD_AI, CHAR(10), ''), CHAR(13), ''), CHAR(9), '')))
  GO

UPDATE DRUG_Mapper_Temp SET CLEANED_PROD_AI =  LEFT(CLEANED_PROD_AI, LEN(CLEANED_PROD_AI)-4) 
WHERE RIGHT (CLEANED_PROD_AI,4) =' NOS';


UPDATE DRUG_Mapper_Temp SET CLEANED_PROD_AI =  LEFT(CLEANED_PROD_AI, LEN(CLEANED_PROD_AI)-4) 
WHERE RIGHT (CLEANED_PROD_AI,4) =' GEL';

UPDATE DRUG_Mapper_Temp SET CLEANED_PROD_AI =  LEFT(CLEANED_PROD_AI, LEN(CLEANED_PROD_AI)-4) 

WHERE RIGHT (CLEANED_PROD_AI,4) =' CAP';

UPDATE DRUG_Mapper_Temp SET CLEANED_PROD_AI =  LEFT(CLEANED_PROD_AI, LEN(CLEANED_PROD_AI)-5) 

WHERE RIGHT (CLEANED_PROD_AI,5) =' JELL';


UPDATE DRUG_Mapper_Temp SET CLEANED_PROD_AI =  LEFT(CLEANED_PROD_AI, LEN(CLEANED_PROD_AI)-4) 
WHERE RIGHT (CLEANED_PROD_AI,4) =' TAB';
GO


UPDATE DRUG_Mapper_Temp SET CLEANED_PROD_AI =  LEFT(CLEANED_PROD_AI, LEN(CLEANED_PROD_AI)-4) 
WHERE RIGHT (CLEANED_PROD_AI,4) =' FOR';
GO

UPDATE DRUG_Mapper_Temp SET CLEANED_PROD_AI =  LEFT(CLEANED_PROD_AI, LEN(CLEANED_PROD_AI)-2) 
WHERE RIGHT (CLEANED_PROD_AI,2) ='//';
GO



UPDATE DRUG_Mapper_Temp SET CLEANED_PROD_AI =  LEFT(CLEANED_PROD_AI, LEN(CLEANED_PROD_AI)-3) 
WHERE RIGHT (CLEANED_PROD_AI,1) ='/';
GO

 UPDATE DRUG_Mapper_Temp
SET CLEANED_PROD_AI =LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(CLEANED_PROD_AI, CHAR(10), ''), CHAR(13), ''), CHAR(9), '')))
  
   UPDATE DRUG_Mapper_Temp
SET CLEANED_PROD_AI =LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(CLEANED_PROD_AI, CHAR(10), ''), CHAR(13), ''), CHAR(9), '')))
  
   UPDATE DRUG_Mapper_Temp
SET CLEANED_PROD_AI =LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(CLEANED_PROD_AI, CHAR(10), ''), CHAR(13), ''), CHAR(9), '')))
